name: Compressor
version: 0.1.0
main: com.solidsilver.papermc.Compressor
author: InspectorElement
description: A small plugin for making large numbers of items manageable
api-version: '1.20'
#commands:
#  compressedCobble:
#    description: Gives the player a block of compressed cobble of the specified level
#    usage: /<command> <level>
#    aliases: [cc]