name: Compressor
version: 0.1.1
main: com.solidsilver.papermc.Compressor
author: InspectorElement
description: A small plugin for making large numbers of blocks manageable
api-version: '1.20'
commands:
  give:
    description: Gives the player a compressed block of the specified level
    usage: /compr <block> <level> (amount)
    aliases: [compr]
    permission: compressor.give
    permission-message: You don't have permission to run this command